# Generated by Django 5.1.4 on 2024-12-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthReports', '0002_clinic_diseases_hospital_qualification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
